/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

 /**
  * @author Akram Alnezami
  * @author Lenaïc Love Hounleba
  */
#include "hellowatt.h"

void
hellowatt_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	client  lenaic_cl;
	strcpy(lenaic_cl.cl_nom, "Lenaïc");
	strcpy(lenaic_cl.cl_prenom, "Hounleba");
	strcpy(lenaic_cl.cl_email, "lenaic.hounleba@example.com");
	strcpy(lenaic_cl.cl_mdp, "motdepasse123");
	strcpy(lenaic_cl.cl_tele, "0612345678");

	int  *result_2;
	auth_creds  lenaic_auth;
	strcpy(lenaic_auth.email, "lenaic.hounleba@example.com");
	strcpy(lenaic_auth.mdp, "motdepasse123");

	int  *result_3;
	update_new_mdp  lenaic_update_mdp;
	strcpy(lenaic_update_mdp.email, "lenaic.hounleba@example.com");
	strcpy(lenaic_update_mdp.new_mdp, "nouveaumotdepasse");

	int  *result_4;
	update_new_tele  lenaic_update_tele;
	strcpy(lenaic_update_tele.email, "lenaic.hounleba@example.com");
	strcpy(lenaic_update_tele.new_tele, "0687654321");

	int  *result_5;
	logement  lenaic_logement;
	strcpy(lenaic_logement.log_email, "lenaic.hounleba@example.com");
	strcpy(lenaic_logement.log_addr, "123 Rue de la Paix, 75000 Paris");
	lenaic_logement.log_surface = 100.0;
	strcpy(lenaic_logement.log_type, "Appartement");
	strcpy(lenaic_logement.log_structure, "Brique");
	
	int  *result_6;
	energie  lenaic_energie;
	strcpy(lenaic_energie.en_email, "lenaic.hounleba@example.com");
	strcpy(lenaic_energie.en_type_cuisson, "Électrique");
	strcpy(lenaic_energie.en_type_chauffage, "Électrique");

	consommation  *result_7;
	requete_mois  lenaic_requete_mois;
	strcpy(lenaic_requete_mois.email, "lenaic.hounleba@example.com");
	lenaic_requete_mois.mois = 1;
	lenaic_requete_mois.annee = 2026;

	comparaison  *result_8;
	requete_mois  lenaic_comparer_consommation;
	strcpy(lenaic_comparer_consommation.email, "lenaic.hounleba@example.com");
	lenaic_comparer_consommation.mois = 1;
	lenaic_comparer_consommation.annee = 2026;

	int  *result_9;
	alerte_mensuelle  lenaic_config_alert_max_depense_par_mois;
	strcpy(lenaic_config_alert_max_depense_par_mois.email, "lenaic.hounleba@example.com");
	lenaic_config_alert_max_depense_par_mois.valeur_max = 100.0;

	int  *result_10;
	auth_creds  lenaic_supprimer_compte;
	strcpy(lenaic_supprimer_compte.email, "lenaic.hounleba@example.com");
	strcpy(lenaic_supprimer_compte.mdp, "motdepasse123");

	client akram_cl;
	int *result_akram_creer;
	consommation *result_11;
    requete_annee akram_requete_annee;
    strcpy(akram_requete_annee.email, "akram.alnezami@example.com");
    akram_requete_annee.annee = 2025;

    consommation *result_12;
    requete_jour akram_requete_jour;
    strcpy(akram_requete_jour.email, "akram.alnezami@example.com");
    akram_requete_jour.jour = 20;
    akram_requete_jour.mois = 1;
    akram_requete_jour.annee = 2026;

    usage_result *result_13;
    requete_mois akram_afficher_usages;
    strcpy(akram_afficher_usages.email, "akram.alnezami@example.com");
    akram_afficher_usages.mois = 1;
    akram_afficher_usages.annee = 2026;
    
    int *result_14;
    pdl_arg akram_pdl;
    strcpy(akram_pdl.email, "akram.alnezami@example.com");
    strcpy(akram_pdl.numero_pdl, "12345678901234");

    int *result_15;
    alerte_journaliere akram_alert_jour;
    strcpy(akram_alert_jour.email, "akram.alnezami@example.com");
    akram_alert_jour.valeur_max = 5.0;

    int *result_16;
    alerte_tension akram_alert_tension;
    strcpy(akram_alert_tension.email, "akram.alnezami@example.com");
    akram_alert_tension.actif = 1;
    
    int *result_17;
    auth_creds akram_auth;
    strcpy(akram_auth.email, "akram.alnezami@example.com");
    strcpy(akram_auth.mdp, "motdepasse456");

#ifndef	DEBUG
	clnt = clnt_create (host, HELLOWATT_PROG, HELLOWATT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/**
	 * scénario de Lenaïc
	 */
	printf("--------------------------------------------------------------------------------\n");
	printf("-------------------------------- Scénario (1)  ---------------------------------\n");	
	printf("--------------------------------------------------------------------------------\n");
	result_1 = creer_compte_1(&lenaic_cl, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la création du compte \n");
	}else if(*result_1 == 0) {
		printf("----- Compte créé avec succès !\n");
	} else if(*result_1 == 1) {
		printf("----- Le client existe déjà !\n");
	} else if(*result_1 == 2) {
		printf("----- La base de données est pleine !\n");
	}

	result_2 = se_connecter_1(&lenaic_auth, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la connexion \n");
	}else if(*result_2 == 0) {
		printf("----- Connexion réussie !\n");
	} else if(*result_2 == 1) {
		printf("----- Identifiants incorrects !\n");
	}

	result_3 = update_mdp_1(&lenaic_update_mdp, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la mise à jour du mot de passe \n");
	}else if(*result_3 == 0) {
		printf("----- Mot de passe mis à jour avec succès !\n");
	} else if(*result_3 == 1) {
		printf("----- Le client n'existe pas !\n");
	}
	
	result_4 = update_tele_1(&lenaic_update_tele, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la mise à jour du numéro de téléphone \n");
	}else if(*result_4 == 0) {
		printf("----- Numéro de téléphone mis à jour avec succès !\n");
	} else if(*result_4 == 1) {
		printf("----- Le client n'existe pas !\n");
	}

	result_5 = saisir_caracteristiques_log_1(&lenaic_logement, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la saisie des caractéristiques du logement \n");
	}else if(*result_5 == 0) {
		printf("----- Caractéristiques du logement saisies avec succès !\n");
	} else if(*result_5 == 1) {
		printf("----- Le client n'existe pas !\n");
	}

	result_6 = saisir_source_energie_1(&lenaic_energie, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la saisie des caractéristiques de l'énergie \n");
	}else if(*result_6 == 0) {
		printf("----- Source d'énergie saisie avec succès !\n");
	} else if(*result_6 == 1) {
		printf("----- Le client n'existe pas !\n");
	}
	
	result_7 = obtenir_consommation_par_mois_1(&lenaic_requete_mois, clnt);
	if (result_7 == (consommation *) NULL) {
		clnt_perror (clnt, "Erreur lors de l'obtention de la consommation par mois \n");
	}else {
		printf("----- Consommation pour %s du mois %d : %.2f kWh\n", lenaic_requete_mois.email, lenaic_requete_mois.mois, result_7->cons_kwh);
	}

	result_8 = comparer_consommation_1(&lenaic_comparer_consommation, clnt);
	if (result_8 == (comparaison *) NULL) {
		clnt_perror (clnt, "Erreur lors de la comparaison de la consommation \n");
	}else {
		printf("----- Comparaison de la consommation pour %s du mois %d : ma conso = %.2f kWh, moyenne région = %.2f kWh\n", lenaic_comparer_consommation.email, lenaic_comparer_consommation.mois, result_8->cmp_ma_conso, result_8->cmp_moyenne_region);
	}

	result_9 = config_alert_max_depense_par_mois_1(&lenaic_config_alert_max_depense_par_mois, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la configuration de l'alerte de dépense maximale par mois \n");
	}else if(*result_9 == 0) {
		printf("----- Alerte de dépense maximale par mois configurée avec succès !\n");
	} else if(*result_9 == 1) {
		printf("----- Le client n'existe pas !\n");
	}
	result_10 = supprimer_compte_1(&lenaic_supprimer_compte, clnt);
	if (result_10 == (int *) NULL) {
		clnt_perror (clnt, "Erreur lors de la suppression du compte \n");
	}else if(*result_10 == 0) {
		printf("----- Compte supprimé avec succès !\n");
	} else if(*result_10 == 1) {
		printf("----- Le client n'existe pas !\n");
	}
	
	/**
     * scenario de Akram
     */
    printf("--------------------------------------------------------------------------------\n");
	printf("-------------------------------- Scénario (2)  ---------------------------------\n");
	printf("--------------------------------------------------------------------------------\n");
    /* compte Akram */
	strcpy(akram_cl.cl_nom, "Alnezami");
	strcpy(akram_cl.cl_prenom, "Akram");
	strcpy(akram_cl.cl_email, "akram.alnezami@example.com");
	strcpy(akram_cl.cl_mdp, "motdepasse456");
	strcpy(akram_cl.cl_tele, "0698765432");
	
	result_akram_creer = creer_compte_1(&akram_cl, clnt);
	if (result_akram_creer == (int *) NULL) {
    	clnt_perror (clnt, "----- erreur lors de la creation du compte Akram \n");
	} else if(*result_akram_creer == 0) {
    	printf("----- compte Akram cree avec succes !\n");
	} else if(*result_akram_creer == 1) {
    	printf("----- Le compte Akram existe deja\n");
	}
     
	result_11 = obtenir_consommation_par_annee_1(&akram_requete_annee, clnt);
    if (result_11 == (consommation *) NULL) {
            clnt_perror (clnt, "----- erreur lors de obtention de la consommation annuelle \n");
    } else {
            printf("----- Consommation annuelle pour %s en %d : %.2f euros, %.2f kWh, %.2f kg CO2 !\n",
            akram_requete_annee.email, akram_requete_annee.annee,
            result_11->cons_euros, result_11->cons_kwh, result_11->cons_co2);
    }
        
    result_12 = obtenir_consommation_par_jour_1(&akram_requete_jour, clnt);
    if (result_12 == (consommation *) NULL) {
            clnt_perror (clnt, "----- erreur lors de lobtention de la consommation journaliere \n");
    } else {
            printf("----- Consommation du %d/%d/%d pour %s : %.2f euros, %.2f kWh, %.2f kg CO2 !\n",
            akram_requete_jour.jour, akram_requete_jour.mois, akram_requete_jour.annee,
            akram_requete_jour.email, result_12->cons_euros, result_12->cons_kwh, result_12->cons_co2);
    }

	result_13 = afficher_usages_1(&akram_afficher_usages, clnt);
    if (result_13 == (usage_result *) NULL) {
            clnt_perror (clnt, "----- erreur lors de laffichage des usages \n");
    } else {
            printf("----- Usages pour %s du mois %d : chauffage=%.2f, cuisson=%.2f, eclairage=%.2f, electromenager=%.2f, autres=%.2f euros !\n",
            akram_afficher_usages.email, akram_afficher_usages.mois,
            result_13->us_chauffage, result_13->us_cuisson, result_13->us_eclairage,
            result_13->us_electromenager, result_13->us_autres);
    }
    
    result_14 = saisir_numero_pdl_1(&akram_pdl, clnt);
    if (result_14 == (int *) NULL) {
            clnt_perror (clnt, "----- erreur lors de la saisie du numero PDL \n");
    } else if(*result_14 == 0) {
            printf("----- Numero PDL enregistree avec succes.\n");
    } else if(*result_14 == 1) {
            printf("----- Ce client nexiste pas !\n");
    }

	result_15 = config_alert_max_depense_par_jour_1(&akram_alert_jour, clnt);
    if (result_15 == (int *) NULL) {
            clnt_perror (clnt, "----- erreur lors de la configuration de lalerte journaliere \n");
    } else if(*result_15 == 0) {
            printf("----- Alerte journaliere configuree avec succes.\n");
    } else if(*result_15 == 1) {
            printf("----- Ce client nexiste pas !\n");
    }
	
	result_16 = config_alert_tension_reseau_1(&akram_alert_tension, clnt);
    if (result_16 == (int *) NULL) {
            clnt_perror (clnt, "----- erreur lors de la configuration de la notification tension reseau \n");
    } else if(*result_16 == 0) {
            printf("----- Notification tension reseau configuree avec succes\n");
    } else if(*result_16 == 1) {
            printf("----- Le client nexiste pas \n");
    }
	
	result_17 = se_deconnecter_1(&akram_auth, clnt);
    if (result_17 == (int *) NULL) {
            clnt_perror (clnt, "----- erreur lors de la deconnexion \n");
    } else if(*result_17 == 0) {
            printf("----- Deconnexion reussie !\n");
    } else if(*result_17 == 1) {
            printf("----- identifiants incorrects !\n");
    }
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	hellowatt_prog_1 (host);
exit (0);
}
