/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hellowatt.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
hellowatt_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		client creer_compte_1_arg;
		auth_creds se_connecter_1_arg;
		update_new_mdp update_mdp_1_arg;
		update_new_tele update_tele_1_arg;
		logement saisir_caracteristiques_log_1_arg;
		energie saisir_source_energie_1_arg;
		requete_mois obtenir_consommation_par_mois_1_arg;
		requete_mois comparer_consommation_1_arg;
		alerte_mensuelle config_alert_max_depense_par_mois_1_arg;
		auth_creds supprimer_compte_1_arg;
		requete_annee obtenir_consommation_par_annee_1_arg;
		requete_jour obtenir_consommation_par_jour_1_arg;
		requete_mois afficher_usages_1_arg;
		pdl_arg saisir_numero_pdl_1_arg;
		alerte_journaliere config_alert_max_depense_par_jour_1_arg;
		alerte_tension config_alert_tension_reseau_1_arg;
		auth_creds se_deconnecter_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case CREER_COMPTE:
		_xdr_argument = (xdrproc_t) xdr_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) creer_compte_1_svc;
		break;

	case SE_CONNECTER:
		_xdr_argument = (xdrproc_t) xdr_auth_creds;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) se_connecter_1_svc;
		break;

	case UPDATE_MDP:
		_xdr_argument = (xdrproc_t) xdr_update_new_mdp;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) update_mdp_1_svc;
		break;

	case UPDATE_TELE:
		_xdr_argument = (xdrproc_t) xdr_update_new_tele;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) update_tele_1_svc;
		break;

	case SAISIR_CARACTERISTIQUES_LOG:
		_xdr_argument = (xdrproc_t) xdr_logement;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) saisir_caracteristiques_log_1_svc;
		break;

	case SAISIR_SOURCE_ENERGIE:
		_xdr_argument = (xdrproc_t) xdr_energie;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) saisir_source_energie_1_svc;
		break;

	case OBTENIR_CONSOMMATION_PAR_MOIS:
		_xdr_argument = (xdrproc_t) xdr_requete_mois;
		_xdr_result = (xdrproc_t) xdr_consommation;
		local = (char *(*)(char *, struct svc_req *)) obtenir_consommation_par_mois_1_svc;
		break;

	case COMPARER_CONSOMMATION:
		_xdr_argument = (xdrproc_t) xdr_requete_mois;
		_xdr_result = (xdrproc_t) xdr_comparaison;
		local = (char *(*)(char *, struct svc_req *)) comparer_consommation_1_svc;
		break;

	case CONFIG_ALERT_MAX_DEPENSE_PAR_MOIS:
		_xdr_argument = (xdrproc_t) xdr_alerte_mensuelle;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) config_alert_max_depense_par_mois_1_svc;
		break;

	case SUPPRIMER_COMPTE:
		_xdr_argument = (xdrproc_t) xdr_auth_creds;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) supprimer_compte_1_svc;
		break;

	case OBTENIR_CONSOMMATION_PAR_ANNEE:
		_xdr_argument = (xdrproc_t) xdr_requete_annee;
		_xdr_result = (xdrproc_t) xdr_consommation;
		local = (char *(*)(char *, struct svc_req *)) obtenir_consommation_par_annee_1_svc;
		break;

	case OBTENIR_CONSOMMATION_PAR_JOUR:
		_xdr_argument = (xdrproc_t) xdr_requete_jour;
		_xdr_result = (xdrproc_t) xdr_consommation;
		local = (char *(*)(char *, struct svc_req *)) obtenir_consommation_par_jour_1_svc;
		break;

	case AFFICHER_USAGES:
		_xdr_argument = (xdrproc_t) xdr_requete_mois;
		_xdr_result = (xdrproc_t) xdr_usage_result;
		local = (char *(*)(char *, struct svc_req *)) afficher_usages_1_svc;
		break;

	case SAISIR_NUMERO_PDL:
		_xdr_argument = (xdrproc_t) xdr_pdl_arg;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) saisir_numero_pdl_1_svc;
		break;

	case CONFIG_ALERT_MAX_DEPENSE_PAR_JOUR:
		_xdr_argument = (xdrproc_t) xdr_alerte_journaliere;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) config_alert_max_depense_par_jour_1_svc;
		break;

	case CONFIG_ALERT_TENSION_RESEAU:
		_xdr_argument = (xdrproc_t) xdr_alerte_tension;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) config_alert_tension_reseau_1_svc;
		break;

	case SE_DECONNECTER:
		_xdr_argument = (xdrproc_t) xdr_auth_creds;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) se_deconnecter_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (HELLOWATT_PROG, HELLOWATT_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, HELLOWATT_PROG, HELLOWATT_VERS, hellowatt_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (HELLOWATT_PROG, HELLOWATT_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, HELLOWATT_PROG, HELLOWATT_VERS, hellowatt_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (HELLOWATT_PROG, HELLOWATT_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
