/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLOWATT_H_RPCGEN
#define _HELLOWATT_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


struct auth_creds {
	char email[200];
	char mdp[30];
};
typedef struct auth_creds auth_creds;

struct update_new_mdp {
	char email[200];
	char new_mdp[30];
};
typedef struct update_new_mdp update_new_mdp;

struct update_new_tele {
	char email[200];
	char new_tele[20];
};
typedef struct update_new_tele update_new_tele;

struct alerte_journaliere {
	char email[200];
	float valeur_max;
};
typedef struct alerte_journaliere alerte_journaliere;

struct requete_mois {
	char email[200];
	int mois;
	int annee;
};
typedef struct requete_mois requete_mois;

struct requete_annee {
	char email[200];
	int annee;
};
typedef struct requete_annee requete_annee;

struct requete_jour {
	char email[200];
	int jour;
	int mois;
	int annee;
};
typedef struct requete_jour requete_jour;

struct alerte_mensuelle {
	char email[200];
	float valeur_max;
};
typedef struct alerte_mensuelle alerte_mensuelle;

struct alerte_tension {
	char email[200];
	int actif;
};
typedef struct alerte_tension alerte_tension;

struct pdl_arg {
	char email[200];
	char numero_pdl[30];
};
typedef struct pdl_arg pdl_arg;

struct client {
	char cl_nom[80];
	char cl_prenom[80];
	char cl_email[200];
	char cl_tele[20];
	char cl_mdp[30];
};
typedef struct client client;

struct logement {
	char log_email[200];
	char log_addr[500];
	float log_surface;
	char log_type[50];
	char log_structure[50];
};
typedef struct logement logement;

struct energie {
	char en_email[200];
	char en_type_cuisson[50];
	char en_type_chauffage[50];
};
typedef struct energie energie;

struct consommation {
	char cons_email[200];
	int cons_jour;
	int cons_mois;
	int cons_annee;
	float cons_euros;
	float cons_kwh;
	float cons_co2;
};
typedef struct consommation consommation;

struct usage_result {
	char us_email[200];
	float us_chauffage;
	float us_cuisson;
	float us_eclairage;
	float us_electromenager;
	float us_autres;
};
typedef struct usage_result usage_result;

struct comparaison {
	char cmp_email[200];
	float cmp_ma_conso;
	float cmp_moyenne_region;
};
typedef struct comparaison comparaison;

#define HELLOWATT_PROG 0x20000001
#define HELLOWATT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREER_COMPTE 1
extern  int * creer_compte_1(client *, CLIENT *);
extern  int * creer_compte_1_svc(client *, struct svc_req *);
#define SE_CONNECTER 2
extern  int * se_connecter_1(auth_creds *, CLIENT *);
extern  int * se_connecter_1_svc(auth_creds *, struct svc_req *);
#define UPDATE_MDP 3
extern  int * update_mdp_1(update_new_mdp *, CLIENT *);
extern  int * update_mdp_1_svc(update_new_mdp *, struct svc_req *);
#define UPDATE_TELE 4
extern  int * update_tele_1(update_new_tele *, CLIENT *);
extern  int * update_tele_1_svc(update_new_tele *, struct svc_req *);
#define SAISIR_CARACTERISTIQUES_LOG 5
extern  int * saisir_caracteristiques_log_1(logement *, CLIENT *);
extern  int * saisir_caracteristiques_log_1_svc(logement *, struct svc_req *);
#define SAISIR_SOURCE_ENERGIE 6
extern  int * saisir_source_energie_1(energie *, CLIENT *);
extern  int * saisir_source_energie_1_svc(energie *, struct svc_req *);
#define OBTENIR_CONSOMMATION_PAR_MOIS 7
extern  consommation * obtenir_consommation_par_mois_1(requete_mois *, CLIENT *);
extern  consommation * obtenir_consommation_par_mois_1_svc(requete_mois *, struct svc_req *);
#define COMPARER_CONSOMMATION 8
extern  comparaison * comparer_consommation_1(requete_mois *, CLIENT *);
extern  comparaison * comparer_consommation_1_svc(requete_mois *, struct svc_req *);
#define CONFIG_ALERT_MAX_DEPENSE_PAR_MOIS 9
extern  int * config_alert_max_depense_par_mois_1(alerte_mensuelle *, CLIENT *);
extern  int * config_alert_max_depense_par_mois_1_svc(alerte_mensuelle *, struct svc_req *);
#define SUPPRIMER_COMPTE 10
extern  int * supprimer_compte_1(auth_creds *, CLIENT *);
extern  int * supprimer_compte_1_svc(auth_creds *, struct svc_req *);
#define OBTENIR_CONSOMMATION_PAR_ANNEE 11
extern  consommation * obtenir_consommation_par_annee_1(requete_annee *, CLIENT *);
extern  consommation * obtenir_consommation_par_annee_1_svc(requete_annee *, struct svc_req *);
#define OBTENIR_CONSOMMATION_PAR_JOUR 12
extern  consommation * obtenir_consommation_par_jour_1(requete_jour *, CLIENT *);
extern  consommation * obtenir_consommation_par_jour_1_svc(requete_jour *, struct svc_req *);
#define AFFICHER_USAGES 13
extern  usage_result * afficher_usages_1(requete_mois *, CLIENT *);
extern  usage_result * afficher_usages_1_svc(requete_mois *, struct svc_req *);
#define SAISIR_NUMERO_PDL 14
extern  int * saisir_numero_pdl_1(pdl_arg *, CLIENT *);
extern  int * saisir_numero_pdl_1_svc(pdl_arg *, struct svc_req *);
#define CONFIG_ALERT_MAX_DEPENSE_PAR_JOUR 15
extern  int * config_alert_max_depense_par_jour_1(alerte_journaliere *, CLIENT *);
extern  int * config_alert_max_depense_par_jour_1_svc(alerte_journaliere *, struct svc_req *);
#define CONFIG_ALERT_TENSION_RESEAU 16
extern  int * config_alert_tension_reseau_1(alerte_tension *, CLIENT *);
extern  int * config_alert_tension_reseau_1_svc(alerte_tension *, struct svc_req *);
#define SE_DECONNECTER 17
extern  int * se_deconnecter_1(auth_creds *, CLIENT *);
extern  int * se_deconnecter_1_svc(auth_creds *, struct svc_req *);
extern int hellowatt_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREER_COMPTE 1
extern  int * creer_compte_1();
extern  int * creer_compte_1_svc();
#define SE_CONNECTER 2
extern  int * se_connecter_1();
extern  int * se_connecter_1_svc();
#define UPDATE_MDP 3
extern  int * update_mdp_1();
extern  int * update_mdp_1_svc();
#define UPDATE_TELE 4
extern  int * update_tele_1();
extern  int * update_tele_1_svc();
#define SAISIR_CARACTERISTIQUES_LOG 5
extern  int * saisir_caracteristiques_log_1();
extern  int * saisir_caracteristiques_log_1_svc();
#define SAISIR_SOURCE_ENERGIE 6
extern  int * saisir_source_energie_1();
extern  int * saisir_source_energie_1_svc();
#define OBTENIR_CONSOMMATION_PAR_MOIS 7
extern  consommation * obtenir_consommation_par_mois_1();
extern  consommation * obtenir_consommation_par_mois_1_svc();
#define COMPARER_CONSOMMATION 8
extern  comparaison * comparer_consommation_1();
extern  comparaison * comparer_consommation_1_svc();
#define CONFIG_ALERT_MAX_DEPENSE_PAR_MOIS 9
extern  int * config_alert_max_depense_par_mois_1();
extern  int * config_alert_max_depense_par_mois_1_svc();
#define SUPPRIMER_COMPTE 10
extern  int * supprimer_compte_1();
extern  int * supprimer_compte_1_svc();
#define OBTENIR_CONSOMMATION_PAR_ANNEE 11
extern  consommation * obtenir_consommation_par_annee_1();
extern  consommation * obtenir_consommation_par_annee_1_svc();
#define OBTENIR_CONSOMMATION_PAR_JOUR 12
extern  consommation * obtenir_consommation_par_jour_1();
extern  consommation * obtenir_consommation_par_jour_1_svc();
#define AFFICHER_USAGES 13
extern  usage_result * afficher_usages_1();
extern  usage_result * afficher_usages_1_svc();
#define SAISIR_NUMERO_PDL 14
extern  int * saisir_numero_pdl_1();
extern  int * saisir_numero_pdl_1_svc();
#define CONFIG_ALERT_MAX_DEPENSE_PAR_JOUR 15
extern  int * config_alert_max_depense_par_jour_1();
extern  int * config_alert_max_depense_par_jour_1_svc();
#define CONFIG_ALERT_TENSION_RESEAU 16
extern  int * config_alert_tension_reseau_1();
extern  int * config_alert_tension_reseau_1_svc();
#define SE_DECONNECTER 17
extern  int * se_deconnecter_1();
extern  int * se_deconnecter_1_svc();
extern int hellowatt_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_auth_creds (XDR *, auth_creds*);
extern  bool_t xdr_update_new_mdp (XDR *, update_new_mdp*);
extern  bool_t xdr_update_new_tele (XDR *, update_new_tele*);
extern  bool_t xdr_alerte_journaliere (XDR *, alerte_journaliere*);
extern  bool_t xdr_requete_mois (XDR *, requete_mois*);
extern  bool_t xdr_requete_annee (XDR *, requete_annee*);
extern  bool_t xdr_requete_jour (XDR *, requete_jour*);
extern  bool_t xdr_alerte_mensuelle (XDR *, alerte_mensuelle*);
extern  bool_t xdr_alerte_tension (XDR *, alerte_tension*);
extern  bool_t xdr_pdl_arg (XDR *, pdl_arg*);
extern  bool_t xdr_client (XDR *, client*);
extern  bool_t xdr_logement (XDR *, logement*);
extern  bool_t xdr_energie (XDR *, energie*);
extern  bool_t xdr_consommation (XDR *, consommation*);
extern  bool_t xdr_usage_result (XDR *, usage_result*);
extern  bool_t xdr_comparaison (XDR *, comparaison*);

#else /* K&R C */
extern bool_t xdr_auth_creds ();
extern bool_t xdr_update_new_mdp ();
extern bool_t xdr_update_new_tele ();
extern bool_t xdr_alerte_journaliere ();
extern bool_t xdr_requete_mois ();
extern bool_t xdr_requete_annee ();
extern bool_t xdr_requete_jour ();
extern bool_t xdr_alerte_mensuelle ();
extern bool_t xdr_alerte_tension ();
extern bool_t xdr_pdl_arg ();
extern bool_t xdr_client ();
extern bool_t xdr_logement ();
extern bool_t xdr_energie ();
extern bool_t xdr_consommation ();
extern bool_t xdr_usage_result ();
extern bool_t xdr_comparaison ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLOWATT_H_RPCGEN */
