/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hellowatt.h"
#include <stdio.h>
#include <string.h>

#define MAX_CLIENTS 100

/********************************
 * simuler une base de données en mémoire pour les clients, logements, énergies et consommations
 */
client clients[MAX_CLIENTS];
int nb_clients = 0;
logement logements[MAX_CLIENTS];
energie energies[MAX_CLIENTS];
consommation consommations[MAX_CLIENTS][12][31]; // consommation par jour pour chaque mois

char pdl_clients[MAX_CLIENTS][30]; // pdl par client
float alert_jour[MAX_CLIENTS]; // alertes par client
int alert_tension_reseau[MAX_CLIENTS];

/********************************
 * Créer un nouveau compte client.
 * Retourne 0 en cas de succès, 1 si le client existe déjà et 2 si la base de données est pleine.
 */
int *
creer_compte_1_svc(client *cl, struct svc_req *rqstp)
{
	static int  result;
	printf("Création de compte pour %s %s \n", cl->cl_prenom, cl->cl_nom);
	/* Vérifier si le client existe déjà */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, cl->cl_email) == 0)
		{
			printf("Le client existe déjà !\n");
			// échec : client existe déjà
			result = 1; 
			return &result;
		}
	}
	/* Ajouter le client à la "base de données" */
	if(nb_clients < MAX_CLIENTS) 
	{
		clients[nb_clients++] = *cl;
		printf("Compte créé avec succès !\n");
		result = 0; // succès
		return &result;
	} else {
		printf("La base de données est pleine !\n");
		result = 2; // échec : base de données pleine
		return &result;
	}
}

/********************************
 * Permettre à un client de se connecter.
 * Retourne 0 en cas de succès, 1 si les identifiants sont incorrects.
 */
int *
se_connecter_1_svc(auth_creds *ident, struct svc_req *rqstp)
{
	static int  result = 1;
	printf("Tentative de connexion pour %s \n", ident->email);
	/* Vérifier les identifiants du client */
	int i;
	for(i=0; i<nb_clients; i++) 
	{
		if(strcmp(clients[i].cl_email, ident->email) == 0 && strcmp(clients[i].cl_mdp, ident->mdp) == 0)
		{
			printf("----- Connexion réussie !\n");
			result = 0; // succès
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Identifiants incorrects !\n");
		result = 1; // échec : identifiants incorrects
		return &result;
	}
}

/********************************
* Mettre à jour le mot de passe d'un client.
* Retourne 0 en cas de succès, 1 si le client n'existe pas.
*/
int *
update_mdp_1_svc(update_new_mdp *new_mdp, struct svc_req *rqstp)
{
	static int  result = 1;
	printf("Mise à jour du mot de passe pour %s \n", new_mdp->email);
	/* Vérifier si le client existe */
	int i;
	for(i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, new_mdp->email) == 0)
		{
			strcpy(clients[i].cl_mdp, new_mdp->new_mdp);
			printf("----- Mot de passe mis à jour avec succès !\n");
			result = 0; // succès
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Le client n'existe pas !\n");
		result = 1;
		return &result;
	}
}

/********************************
 * Mettre à jour le numéro de téléphone d'un client.
 * Retourne 0 en cas de succès, 1 si le client n'existe pas.
 */
int *
update_tele_1_svc(update_new_tele *new_tele, struct svc_req *rqstp)
{
	static int  result = 1;
	printf("Mise à jour du numéro de téléphone pour %s \n", new_tele->email);
	/* Vérifier si le client existe */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, new_tele->email) == 0)
		{
			strcpy(clients[i].cl_tele, new_tele->new_tele);
			printf("----- Numéro de téléphone mis à jour avec succès !\n");
			result = 0; // succès
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Le client n'existe pas !\n");
		result = 1;
		return &result;
	}
}

/********************************
 * Saisir les caractéristiques du logement d'un client.
 * Retourne 0 en cas de succès, 1 si le client n'existe pas.
*/
int *
saisir_caracteristiques_log_1_svc(logement *log, struct svc_req *rqstp)
{
	static int result = 1;
	printf("Saisie des caractéristiques du logement pour %s \n", log->log_email);
	/* Vérifier si le client existe */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, log->log_email) == 0)
		{
			logements[i] = *log;
			printf("----- Caractéristiques du logement saisies avec succès !\n");
			result = 0; // succès
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Le client n'existe pas !\n");
		result = 1;
		return &result;
	}
}

/**
 * Saisir les sources d'énergie utilisées par un client.
 * Retourne 0 en cas de succès, 1 si le client n'existe pas
 */
int *
saisir_source_energie_1_svc(energie *en, struct svc_req *rqstp)
{
	static int  result = 1;
	printf("Saisie des sources d'énergie pour %s \n", en->en_email);
	/* Vérifier si le client existe */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, en->en_email) == 0)
		{
			energies[i] = *en;
			printf("----- sources d'énergie saisies avec succès !\n");
			result = 0;
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Le client n'existe pas !\n");
		result = 1;
		return &result;
	}
}

/**
 * Obtenir la consommation d'un client pour un mois donné.
 * Retourne un struct consommation contenant les détails de la consommation.
 */
consommation *
obtenir_consommation_par_mois_1_svc(requete_mois *mois, struct svc_req *rqstp)
{
	static consommation  result = {0};
	int res = 1;
	printf("Obtention de la consommation pour %s du mois %d \n", mois->email, mois->mois);
	/* Vérifier si le client existe */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, mois->email) == 0)
		{
			// retourner la consommation du premier jour du mois pour simplifier
			result = consommations[i][mois->mois-1][0];
			printf("----- Consommation obtenue avec succès !\n");
			res = 0;
			return &result;
		}
	}
	if(res == 1) {
		printf("----- Le client n'existe pas !\n");
	}
	return &result;
}

/**
 * Comparer la consommation d'un client pour un mois donné avec la moyenne générale de consommation dans la base de données.
 * Retourne un struct comparaison contenant les détails de la comparaison.
 */
comparaison *
comparer_consommation_1_svc(requete_mois *mois, struct svc_req *rqstp)
{
    static comparaison result = {0};
	int res = 1;
    memset(&result, 0, sizeof(comparaison));
	printf("Comparaison de la consommation pour %s du mois %d \n", mois->email, mois->mois);
	/* Vérifier si le client existe */
    for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, mois->email) == 0)
        {
			printf("----- Client trouvé, calcul de la comparaison en cours...\n");
            float cons_client = consommations[i][mois->mois-1][0].cons_kwh;
            float cons_moyenne = 0;
            int nb_consommations = 0;
            for(int j=0; j<nb_clients; j++)
            {
                if(consommations[j][mois->mois-1][0].cons_kwh > 0)
                {
                    cons_moyenne += consommations[j][mois->mois-1][0].cons_kwh;
                    nb_consommations++;
                }
            }
            if(nb_consommations > 0) cons_moyenne /= nb_consommations;
            
            strcpy(result.cmp_email, mois->email);
            result.cmp_ma_conso = cons_client;
            result.cmp_moyenne_region = cons_moyenne;
			res = 0;
            return &result;
        }
    }
	if(res == 1) {
		printf("----- Le client n'existe pas !\n");
	}
    return &result;
}

/**
 * Configurer une alerte de dépense maximale par mois pour un client.
 * Retourne 0 en cas de succès, 1 si le client n'existe pas.
 */
int *
config_alert_max_depense_par_mois_1_svc(alerte_mensuelle *alert, struct svc_req *rqstp)
{
	static int  result = 1;
	printf("Configuration de l'alerte de dépense maximale par mois pour %s \n", alert->email);
	/* Vérifier si le client existe */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, alert->email) == 0)
		{
			// ici on devrait stocker l'alerte dans la base de données, mais pour simplifier on se contente de retourner un succès
			printf("----- Alerte configurée avec succès !\n");
			result = 0;
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Le client n'existe pas !\n");
		result = 1;
		return &result;
	}
}

/**
 * Supprimer le compte d'un client.
 * Retourne 0 en cas de succès, 1 si le client n'existe pas
 */
int *
supprimer_compte_1_svc(auth_creds *cl, struct svc_req *rqstp)
{
	static int  result;
	printf("Suppression du compte pour %s \n", cl->email);
	/* Vérifier si le client existe */
	for(int i=0; i<nb_clients; i++)
	{
		if(strcmp(clients[i].cl_email, cl->email) == 0)
		{
			// supprimer le client de la "base de données" 
			for(int j=i; j<nb_clients-1; j++)
			{
				clients[j] = clients[j+1];
				logements[j] = logements[j+1];
				energies[j] = energies[j+1];
				for(int m=0; m<12; m++)
				{
					for(int d=0; d<31; d++)
					{
						consommations[j][m][d] = consommations[j+1][m][d];
					}
				}
			}
			nb_clients--;
			printf("----- Compte supprimé avec succès !\n");
			result = 0;
			return &result;
		}
	}
	if(result == 1) {
		printf("----- Le client n'existe pas !\n");
		result = 1;
		return &result;
	}
	return &result;
}


/**
 * Obtenir la consommation totale dun client pour une annee en additionnant les jours
 * Retourne un struct consommation avec les totaux annuels
 */
consommation *
obtenir_consommation_par_annee_1_svc(requete_annee *argp, struct svc_req *rqstp)
{
	static consommation  result;
	int res = 1;
	memset(&result, 0, sizeof(consommation));
		
	struct consommation akram;
	akram.cons_jour = 20;
	akram.cons_mois = 1;
	akram.cons_annee = 2025;
	akram.cons_euros = 10.0;
	akram.cons_kwh = 2.0;
	akram.cons_co2 = 0.5;
	strcpy(akram.cons_email, "akram.alnezami@example.com");

	consommations[0][0][19] = akram; // consommation du 20/01/2026 pour Akram

    printf("Obtention de la consommation annuelle pour %s, annee %d \n", argp->email, argp->annee);
	for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0)
        {
                strcpy(result.cons_email, argp->email);
                result.cons_annee = argp->annee;
                result.cons_mois = -1;
                result.cons_jour = -1;
                /* additionner toutes les consommation journalieres de l'annee */
                for(int m=0; m<12; m++)
                {
                        for(int d=0; d<31; d++)
                        {
                                result.cons_euros += consommations[i][m][d].cons_euros;
                                result.cons_kwh += consommations[i][m][d].cons_kwh;
                                result.cons_co2 += consommations[i][m][d].cons_co2;
                        }
                }
                printf("Consommation annuelle : %.2f euros, %.2f kWh, %.2f kg CO2 !\n",
                        result.cons_euros, result.cons_kwh, result.cons_co2);
                res = 0;
                return &result;
        }
    }
    
	if(res == 1) {
                printf("Le client n'existe pas !\n");
    }
    return &result;
}


/**
 * Obtenir la consommation dun client pour un jour donne
 * Retourne un struct consommation avec les details du jour
 */
consommation *
obtenir_consommation_par_jour_1_svc(requete_jour *argp, struct svc_req *rqstp)
{
	static consommation  result;
	int res = 1;
    memset(&result, 0, sizeof(consommation));
    printf("Obtention de la consommation pour %s du %d/%d/%d \n", argp->email, argp->jour, argp->mois, argp->annee);

	for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0)
        {
                result = consommations[i][argp->mois-1][argp->jour-1];
                strcpy(result.cons_email, argp->email);
                result.cons_jour = argp->jour;
                result.cons_mois = argp->mois;
                result.cons_annee = argp->annee;
                printf("Consommation du jour : %.2f euros, %.2f kWh, %.2f kg CO2 \n", result.cons_euros, result.cons_kwh, result.cons_co2);
                res = 0;
                return &result;
        }
    }
    if(res == 1) {
            printf("Le client nexiste pas \n");
    }
    return &result;
}


/**
 * Afficher la repartition des usages dun client pour un mois 
 * retourne un struct usage_result avec les montants par poste
 */
usage_result *
afficher_usages_1_svc(requete_mois *argp, struct svc_req *rqstp)
{
	static usage_result  result;
	int res = 1;
    memset(&result, 0, sizeof(usage_result));
    printf("les usages pour %s du mois %d/%d \n", argp->email, argp->mois, argp->annee);
    
	for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0)
        {
                strcpy(result.us_email, argp->email);
                /* la consommation totale du mois */
                float total = 0;
                for(int d=0; d<31; d++)
                {
                        total += consommations[i][argp->mois-1][d].cons_euros;
                }
                /* reparttition par poste de consommation */
                result.us_chauffage = total * 0.40; /* 40% chauffage */
                result.us_cuisson = total * 0.15; /* 15% cuisson */
                result.us_eclairage = total * 0.10; /* 10% éclairage */
                result.us_electromenager = total * 0.25; /* 25% électroménager */
                result.us_autres = total * 0.10; /* 10% autres */
                printf("Usages : chauffage=%.2f, cuisson=%.2f, eclairage=%.2f, electromenager=%.2f, autres=%.2f euros \n",
                        result.us_chauffage, result.us_cuisson, result.us_eclairage,
                        result.us_electromenager, result.us_autres);
                res = 0;
                return &result;
        }
     }
     if(res == 1) {
           printf("Le client nexiste pas .\n");
     }

	return &result;
}


/**
 * Saisir le numero PLD du compteur Linky dun client
 * Retourne 0 en cas de succes, 1 si le client nexiste pas
 */
int *
saisir_numero_pdl_1_svc(pdl_arg *argp, struct svc_req *rqstp)
{
	static int  result;
	
	printf("Saisie du numero PDL pour %s \n", argp->email);
    for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0)
        {
                strcpy(pdl_clients[i], argp->numero_pdl);
                printf("Numero PDL enregistre avec succes : %s !\n", argp->numero_pdl);
                result = 0;
                return &result;
        }
    }
    printf("Le client nexiste pas \n");
    result = 1;

	return &result;
}

/**
 * Configurer une alerte de depense maximale par jour pour un client
 * Retourne 0 en cas de succes, 1 si le client nexiste pas.
 */
int *
config_alert_max_depense_par_jour_1_svc(alerte_journaliere *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Configuration de lalerte journaliere pour %s \n", argp->email);
    for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0)
        {
                alert_jour[i] = argp->valeur_max;
                printf("alerte journaliere configuree avec succes : %.2f euros/jour !\n", argp->valeur_max);
                result = 0;
                return &result;
        }
    }
    printf("le client nexiste pas.\n");
    result = 1;

	return &result;
}

/**
 * activer ou desactiver notifications de tension reseau pour un client
 * Retourne 0 en cas de succes, 1 si le client nexiste pas.
 */
int *
config_alert_tension_reseau_1_svc(alerte_tension *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Configuration de la notification tension reseau pour %s \n", argp->email);
    for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0)
        {
                alert_tension_reseau[i] = argp->actif;
                if(argp->actif == 1)
                        printf("Notifications tension rseau activees avec succes\n");
                else
                        printf("Notifications tension reseau desactivees\n");
                result = 0;
                return &result;
        }
    }
    printf("le client n'existe pas !\n");
    result = 1;

	return &result;
}

/**
 * Deconnecter un client
 * Retourne 0 en cas de succes, 1 si les identifiants sont incorrects
 */
int *
se_deconnecter_1_svc(auth_creds *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Deconnexion de %s \n", argp->email);
    for(int i=0; i<nb_clients; i++)
    {
        if(strcmp(clients[i].cl_email, argp->email) == 0 && strcmp(clients[i].cl_mdp, argp->mdp) == 0)
        {
                printf("deconnexion reussi !\n");
                result = 0;
                return &result;
        }
    }
        printf("Identifiants incorrects\n");
        result = 1;

	return &result;
}
