/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "hellowatt.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
creer_compte_1(client *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CREER_COMPTE,
		(xdrproc_t) xdr_client, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
se_connecter_1(auth_creds *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SE_CONNECTER,
		(xdrproc_t) xdr_auth_creds, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
update_mdp_1(update_new_mdp *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPDATE_MDP,
		(xdrproc_t) xdr_update_new_mdp, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
update_tele_1(update_new_tele *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPDATE_TELE,
		(xdrproc_t) xdr_update_new_tele, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
saisir_caracteristiques_log_1(logement *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SAISIR_CARACTERISTIQUES_LOG,
		(xdrproc_t) xdr_logement, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
saisir_source_energie_1(energie *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SAISIR_SOURCE_ENERGIE,
		(xdrproc_t) xdr_energie, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

consommation *
obtenir_consommation_par_mois_1(requete_mois *argp, CLIENT *clnt)
{
	static consommation clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENIR_CONSOMMATION_PAR_MOIS,
		(xdrproc_t) xdr_requete_mois, (caddr_t) argp,
		(xdrproc_t) xdr_consommation, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

comparaison *
comparer_consommation_1(requete_mois *argp, CLIENT *clnt)
{
	static comparaison clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, COMPARER_CONSOMMATION,
		(xdrproc_t) xdr_requete_mois, (caddr_t) argp,
		(xdrproc_t) xdr_comparaison, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
config_alert_max_depense_par_mois_1(alerte_mensuelle *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CONFIG_ALERT_MAX_DEPENSE_PAR_MOIS,
		(xdrproc_t) xdr_alerte_mensuelle, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
supprimer_compte_1(auth_creds *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUPPRIMER_COMPTE,
		(xdrproc_t) xdr_auth_creds, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

consommation *
obtenir_consommation_par_annee_1(requete_annee *argp, CLIENT *clnt)
{
	static consommation clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENIR_CONSOMMATION_PAR_ANNEE,
		(xdrproc_t) xdr_requete_annee, (caddr_t) argp,
		(xdrproc_t) xdr_consommation, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

consommation *
obtenir_consommation_par_jour_1(requete_jour *argp, CLIENT *clnt)
{
	static consommation clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENIR_CONSOMMATION_PAR_JOUR,
		(xdrproc_t) xdr_requete_jour, (caddr_t) argp,
		(xdrproc_t) xdr_consommation, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

usage_result *
afficher_usages_1(requete_mois *argp, CLIENT *clnt)
{
	static usage_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AFFICHER_USAGES,
		(xdrproc_t) xdr_requete_mois, (caddr_t) argp,
		(xdrproc_t) xdr_usage_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
saisir_numero_pdl_1(pdl_arg *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SAISIR_NUMERO_PDL,
		(xdrproc_t) xdr_pdl_arg, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
config_alert_max_depense_par_jour_1(alerte_journaliere *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CONFIG_ALERT_MAX_DEPENSE_PAR_JOUR,
		(xdrproc_t) xdr_alerte_journaliere, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
config_alert_tension_reseau_1(alerte_tension *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CONFIG_ALERT_TENSION_RESEAU,
		(xdrproc_t) xdr_alerte_tension, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
se_deconnecter_1(auth_creds *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SE_DECONNECTER,
		(xdrproc_t) xdr_auth_creds, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
