/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hellowatt.h"

bool_t
xdr_auth_creds (XDR *xdrs, auth_creds *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mdp, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_new_mdp (XDR *xdrs, update_new_mdp *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->new_mdp, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_new_tele (XDR *xdrs, update_new_tele *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->new_tele, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_alerte_journaliere (XDR *xdrs, alerte_journaliere *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valeur_max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_requete_mois (XDR *xdrs, requete_mois *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_requete_annee (XDR *xdrs, requete_annee *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_requete_jour (XDR *xdrs, requete_jour *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_alerte_mensuelle (XDR *xdrs, alerte_mensuelle *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valeur_max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_alerte_tension (XDR *xdrs, alerte_tension *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->actif))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pdl_arg (XDR *xdrs, pdl_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->numero_pdl, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cl_nom, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cl_prenom, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cl_email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cl_tele, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cl_mdp, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_logement (XDR *xdrs, logement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->log_email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->log_addr, 500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->log_surface))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->log_type, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->log_structure, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_energie (XDR *xdrs, energie *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->en_email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->en_type_cuisson, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->en_type_chauffage, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_consommation (XDR *xdrs, consommation *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->cons_email, 200,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->cons_jour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cons_mois))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cons_annee))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->cons_jour);
		IXDR_PUT_LONG(buf, objp->cons_mois);
		IXDR_PUT_LONG(buf, objp->cons_annee);
		}
		 if (!xdr_float (xdrs, &objp->cons_euros))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->cons_kwh))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->cons_co2))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->cons_email, 200,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->cons_jour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cons_mois))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cons_annee))
				 return FALSE;

		} else {
		objp->cons_jour = IXDR_GET_LONG(buf);
		objp->cons_mois = IXDR_GET_LONG(buf);
		objp->cons_annee = IXDR_GET_LONG(buf);
		}
		 if (!xdr_float (xdrs, &objp->cons_euros))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->cons_kwh))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->cons_co2))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->cons_email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cons_jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cons_mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cons_annee))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cons_euros))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cons_kwh))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cons_co2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_usage_result (XDR *xdrs, usage_result *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->us_email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->us_chauffage))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->us_cuisson))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->us_eclairage))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->us_electromenager))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->us_autres))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_comparaison (XDR *xdrs, comparaison *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cmp_email, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cmp_ma_conso))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cmp_moyenne_region))
		 return FALSE;
	return TRUE;
}
